import Foundation
import Testing
@testable import KokoroSwift

/// Verifies the LFM2 hybrid port against a fixture generated by the MLX Python
/// reference (kikiri-tts scripts/convert_lfm2_to_mlx.py), which is verified
/// against Hugging Face transformers (55/55 argmax, max|Δlogit|=1e-4).
///
/// Requires the converted model directory; skipped when absent.
@Suite struct LFM2ModelTests {
  static let modelDir = URL(fileURLWithPath: NSString(
    string: "~/Documents/models/lfm2").expandingTildeInPath)
  static let system = "You are a helpful assistant."

  struct FixtureCase: Decodable {
    let user: String
    let promptIds: [Int]
    let outputIds: [Int]
    let reply: String
  }

  static func loadFixture() -> [FixtureCase]? {
    guard let data = try? Data(contentsOf: modelDir.appendingPathComponent("swift_test_fixture.json"))
    else { return nil }
    return try? JSONDecoder().decode([FixtureCase].self, from: data)
  }

  @Test func matchesPythonReference() throws {
    guard let fixture = Self.loadFixture(),
          FileManager.default.fileExists(
            atPath: Self.modelDir.appendingPathComponent("lfm2_230m_fp16.safetensors").path)
    else {
      print("lfm2 model dir not found — skipping")
      return
    }

    let model = try LFM2Model(
      modelPath: Self.modelDir.appendingPathComponent("lfm2_230m_fp16.safetensors"),
      tokenizerPath: Self.modelDir.appendingPathComponent("tokenizer.json"))

    for testCase in fixture {
      // 1. Tokenizer + template: prompt ids must match exactly
      let promptIds = model.buildPrompt(
        system: Self.system,
        turns: [LFM2Model.Turn(role: "user", content: testCase.user)])
      #expect(promptIds == testCase.promptIds, "prompt ids for: \(testCase.user)")

      // 2. Greedy generation must match the Python fp16 reference
      let outputIds = model.generate(
        promptIds: promptIds, maxTokens: 60, stop: [model.tokenizer.imEndId])
      #expect(outputIds == testCase.outputIds, "output ids for: \(testCase.user)")

      // 3. Decode round-trip
      #expect(model.tokenizer.decode(outputIds).trimmingCharacters(in: .whitespacesAndNewlines)
              == testCase.reply, "reply for: \(testCase.user)")
    }
  }
}
