import Foundation
import Testing
@testable import KokoroSwift

/// Verifies the Nawah LLM port against a fixture generated by the MLX Python
/// reference (kikiri-tts scripts/convert_nawah_to_mlx.py), which is itself
/// verified token-for-token against Hugging Face transformers.
///
/// Requires the converted model directory; skipped when absent.
@Suite struct NawahLLMTests {
  static let modelDir = URL(fileURLWithPath: NSString(
    string: "~/Documents/models/nawah").expandingTildeInPath)

  struct FixtureCase: Decodable {
    let user: String
    let promptIds: [Int]
    let outputIds: [Int]
    let reply: String
  }

  static func loadFixture() -> [FixtureCase]? {
    guard let data = try? Data(contentsOf: modelDir.appendingPathComponent("swift_test_fixture.json"))
    else { return nil }
    return try? JSONDecoder().decode([FixtureCase].self, from: data)
  }

  @Test func matchesPythonReference() throws {
    guard let fixture = Self.loadFixture(),
          FileManager.default.fileExists(
            atPath: Self.modelDir.appendingPathComponent("nawah_50m_fp16.safetensors").path)
    else {
      print("nawah model dir not found — skipping")
      return
    }

    let llm = try NawahLLM(
      modelPath: Self.modelDir.appendingPathComponent("nawah_50m_fp16.safetensors"),
      tokenizerPath: Self.modelDir.appendingPathComponent("tokenizer.json"))
    let tokenizer = try NawahTokenizer(
      tokenizerPath: Self.modelDir.appendingPathComponent("tokenizer.json"))

    for testCase in fixture {
      // 1. Tokenizer: rebuilding the ChatML prompt must give identical ids
      var promptIds: [Int] = [NawahTokenizer.imStartId]
      promptIds += tokenizer.encode("system\n" + NawahLLM.defaultSystemPrompt)
      promptIds.append(NawahTokenizer.imEndId)
      promptIds += tokenizer.encode("\n")
      promptIds.append(NawahTokenizer.imStartId)
      promptIds += tokenizer.encode("user\n" + testCase.user)
      promptIds.append(NawahTokenizer.imEndId)
      promptIds += tokenizer.encode("\n")
      promptIds.append(NawahTokenizer.imStartId)
      promptIds += tokenizer.encode("assistant\n")
      #expect(promptIds == testCase.promptIds, "prompt ids for: \(testCase.user)")

      // 2. Greedy generation must match the Python fp16 reference
      let outputIds = llm.generate(promptIds: promptIds, maxTokens: 60)
      #expect(outputIds == testCase.outputIds, "output ids for: \(testCase.user)")

      // 3. Decode round-trip
      #expect(tokenizer.decode(outputIds).trimmingCharacters(in: .whitespacesAndNewlines)
              == testCase.reply, "reply for: \(testCase.user)")
    }
  }
}
